# Generated by Django 4.2 on 2023-05-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_gmail_contact_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
