# Generated by Django 4.2 on 2023-05-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='contact',
            name='my_number',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=30),
        ),
    ]
