# Generated by Django 4.2 on 2023-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project name')),
                ('project_link', models.URLField()),
                ('url_enabled', models.BooleanField()),
                ('project_git', models.URLField()),
                ('cover_img', models.ImageField(upload_to='cover_imgs')),
                ('description', models.TextField()),
                ('framework', models.CharField(choices=[('django', 'Django'), ('springboot', 'Springboot'), ('nodejs', 'Node js'), ('laravel', 'Laravel')], max_length=100)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
