# Generated by Django 4.2 on 2023-04-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_desabled_link_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desabled_link_msg',
            new_name='disabled_link_msg',
        ),
    ]
