# Generated by Django 4.2 on 2023-05-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='contact_information',
            field=models.EmailField(max_length=254),
        ),
    ]
